name: Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Lint
        run: |
          yarn --frozen-lockfile
          yarn lint
        env:
          CI: true
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build
        run: |
          yarn --frozen-lockfile --ignore-scripts
          yarn build
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          yarn --frozen-lockfile --ignore-scripts
          yarn test
        env:
          CI: true

  test-example:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test example
        run: |
          yarn
          cd example 
          yarn
          yarn test
        env:
          CI: true

  publish:
    runs-on: ubuntu-latest

    needs: [test, test-example]

    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: |
          yarn --frozen-lockfile
          yarn publish --non-interactive
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
